- pom.xml
> chore: set pom version to 0.0.1-SNAPSHOT ready for auto release

- .github/labeler.yml
- .github/workflows/pr-labeler.yaml
> chore: add labeler config ready for jep-229

- README.md
> fix: correct build status labels

- README.md
> fix: build status icon should be based off main

- .github/workflows/cd.yaml
> feat: initial alpha release

- .mvn/extensions.xml
This should disable the "dirty" check when performing the release.
> chore: remove changelist extensions configuration

- README.md
> chore: update build label location

- src/main/java/io/jenkins/plugins/conventionalcommits/NextVersionStep.java
- src/test/java/io/jenkins/plugins/conventionalcommits/JenkinsTest.java
> chore: tests to cover use in a declarative pipeline

- README.md
> fix: correct the status badge on the readme

- src/main/java/io/jenkins/plugins/conventionalcommits/ConventionalCommits.java
- src/test/java/io/jenkins/plugins/conventionalcommits/ConventionalCommitsTest.java
Hi added compare to !: for breaking change and compare with footer BREAKING CHANGE to identify as breaking change. [Related Issue](https://github.com/jenkinsci/conventional-commits-plugin/issues/22)
> feat: add breaking change footer and !:

- pom.xml
- src/main/java/io/jenkins/plugins/conventionalcommits/process/DefaultProcessHelper.java
- src/main/java/io/jenkins/plugins/conventionalcommits/process/ProcessHelper.java
- src/main/java/io/jenkins/plugins/conventionalcommits/utils/CurrentVersion.java
- src/main/java/io/jenkins/plugins/conventionalcommits/utils/GradleProjectType.java
- src/main/java/io/jenkins/plugins/conventionalcommits/utils/MavenProjectType.java
- src/main/java/io/jenkins/plugins/conventionalcommits/utils/ProcessHelper.java
- src/main/java/io/jenkins/plugins/conventionalcommits/utils/ProjectType.java
- src/main/java/io/jenkins/plugins/conventionalcommits/utils/ProjectTypeFactory.java
- src/test/java/io/jenkins/plugins/conventionalcommits/utils/CurrentVersionTest.java
- src/test/java/io/jenkins/plugins/conventionalcommits/utils/ProjectTypeTest.java
fixes #19 
This PR adds the following:
1. GradleProjectType class extending the ProjectType abstract class
2. Support of the project in the factory class
3. Tests for the same :)
> feat: add build.gradle support

- src/main/java/io/jenkins/plugins/conventionalcommits/utils/MakeProjectType.java
- src/main/java/io/jenkins/plugins/conventionalcommits/utils/ProjectTypeFactory.java
- src/test/java/io/jenkins/plugins/conventionalcommits/utils/CurrentVersionTest.java
- src/test/java/io/jenkins/plugins/conventionalcommits/utils/ProjectTypeTest.java
fixes #21 
This pull request:
1. Reads current version from a `Makefile`
2. Adds relevant tests
**Note:** _Only static versions supported for now_
> feat: add Make project type

- .github/workflows/spotbugs.yml
- src/main/java/io/jenkins/plugins/conventionalcommits/utils/MakeProjectType.java
> fix: spotbugs issue - platform encoding

- pom.xml
- src/main/java/io/jenkins/plugins/conventionalcommits/utils/NpmProjectType.java
- src/main/java/io/jenkins/plugins/conventionalcommits/utils/ProjectTypeFactory.java
- src/test/java/io/jenkins/plugins/conventionalcommits/utils/CurrentVersionTest.java
- src/test/java/io/jenkins/plugins/conventionalcommits/utils/ProjectTypeTest.java
Fix #18
The version attribut is get in the package.json.
> feat: Read current version for a NPM project

- pom.xml
- src/main/java/io/jenkins/plugins/conventionalcommits/ConventionalCommits.java
- src/main/java/io/jenkins/plugins/conventionalcommits/NextVersionStep.java
- src/main/java/io/jenkins/plugins/conventionalcommits/process/DefaultProcessHelper.java
- src/main/java/io/jenkins/plugins/conventionalcommits/process/ProcessHelper.java
- src/main/java/io/jenkins/plugins/conventionalcommits/utils/CurrentVersion.java
- src/main/java/io/jenkins/plugins/conventionalcommits/utils/GradleProjectType.java
- src/main/java/io/jenkins/plugins/conventionalcommits/utils/LogUtils.java
- src/main/java/io/jenkins/plugins/conventionalcommits/utils/MakeProjectType.java
- src/main/java/io/jenkins/plugins/conventionalcommits/utils/MavenProjectType.java
- src/main/java/io/jenkins/plugins/conventionalcommits/utils/NpmProjectType.java
- src/main/java/io/jenkins/plugins/conventionalcommits/utils/ProjectType.java
- src/main/java/io/jenkins/plugins/conventionalcommits/utils/ProjectTypeFactory.java
- src/test/java/io/jenkins/plugins/conventionalcommits/ConventionalCommitsTest.java
- src/test/java/io/jenkins/plugins/conventionalcommits/JenkinsTest.java
- src/test/java/io/jenkins/plugins/conventionalcommits/utils/CurrentVersionTest.java
- src/test/java/io/jenkins/plugins/conventionalcommits/utils/ProjectTypeTest.java
fixes #59 
This PR:
1. Fixes google checkstyle bugs
2. Adds googel_checks to pom.xml
Output of `mvn checkstyle:check`:
Output of `mvn test`:
> fix: fix checkstyle bugs

- README.md
> fix: corrected the downloads badge

- src/main/java/io/jenkins/plugins/conventionalcommits/utils/ProjectTypeFactory.java
- src/main/java/io/jenkins/plugins/conventionalcommits/utils/PythonProjectType.java
- src/test/java/io/jenkins/plugins/conventionalcommits/utils/CurrentVersionTest.java
- src/test/java/io/jenkins/plugins/conventionalcommits/utils/ProjectTypeTest.java
fixes #48 
This PR: 
1. Adds skeleton code for python project type
2. Tests for the same
Pending work (to be fixed/merged with next PR)
1. Adding support via `pyproject.toml` see #49 
2. Update current version reading from `setup.py` (discussion needed)
> feat: add python project type

- pom.xml
- src/main/java/io/jenkins/plugins/conventionalcommits/dto/PyProjectTOML.java
- src/main/java/io/jenkins/plugins/conventionalcommits/utils/PythonProjectType.java
- src/test/java/io/jenkins/plugins/conventionalcommits/utils/CurrentVersionTest.java
- src/test/java/io/jenkins/plugins/conventionalcommits/utils/ProjectTypeTest.java
fixes #49
This PR:
1. reads `pyproject.toml`
2. extracts and returns the `version` field 
3. adds required tests
> feat: add python pyproject.toml support

- pom.xml
- src/main/java/io/jenkins/plugins/conventionalcommits/dto/HelmChart.java
- src/main/java/io/jenkins/plugins/conventionalcommits/utils/HelmProjectType.java
- src/main/java/io/jenkins/plugins/conventionalcommits/utils/ProjectTypeFactory.java
- src/test/java/io/jenkins/plugins/conventionalcommits/utils/CurrentVersionTest.java
- src/test/java/io/jenkins/plugins/conventionalcommits/utils/ProjectTypeTest.java
Add the capability to get the current version of an Helm's chart (i.e read the `version` attribute of the file `Chart.yaml`)
fix #20
> feat: Current version for Helm project type

- pom.xml
> fix: use the jackson api plugin for dependencies

- .github/workflows/javadoc.yml
- .github/workflows/spotbugs.yml
- src/main/java/io/jenkins/plugins/conventionalcommits/utils/ProjectTypeFactory.java
> fix: correct invalid javadoc, add a check to validate

- src/main/java/io/jenkins/plugins/conventionalcommits/NextVersionStep.java
- src/main/java/io/jenkins/plugins/conventionalcommits/utils/CurrentVersion.java
- src/test/java/io/jenkins/plugins/conventionalcommits/utils/CurrentVersionTest.java
fixes #89 
This PR adds:
1. logging in case of version mismatch
2. updates CurrentVersion accordingly --> Later of version read from config file and latest tag
3. tests for the same
Sample warning message
PS: Added the missing article (the) before configuration file in the above warning message.
> feat: add version mismatch handler

- README.md
- src/main/java/io/jenkins/plugins/conventionalcommits/utils/NpmProjectType.java
- src/test/java/io/jenkins/plugins/conventionalcommits/utils/NpmProjectTypeTest.java
fix #86 
If optional parameter `ẁriteVersion` is set to `true` then write back to the _package.json_ the next calculated version.
> feat: Write version to a package.json

- README.md
fix #96 
Example with a scripted pipeline.
@ADI10HERO tell me if is it what you want :wink:
> feat: Add scripted pipeline example

- README.md
> docs(readme): correct github issue tracker link

- .github/CONTRIBUTING.md
- README.md
This PR adds `CONTRIBUTING.md` to the repository.
Fixes #70
> docs: Add CONTRIBUTING.md

- src/main/java/io/jenkins/plugins/conventionalcommits/utils/MakeProjectType.java
- src/test/java/io/jenkins/plugins/conventionalcommits/utils/MakeProjectTypeTest.java
* Fixes #112 
* Added writeNextVersion method for Make Project
* Added Testcases for the Make project
> feat: Add write next version support for make projects

- src/main/java/io/jenkins/plugins/conventionalcommits/utils/PythonProjectType.java
- src/test/java/io/jenkins/plugins/conventionalcommits/utils/PythonProjectTypeTest.java
Fix #139 
If several file of cinfiguration exist, return the first attribute version found (order : setup.py > setup.cg > pyproject.toml)
> feat: Several python configuration files

- pom.xml
Fix the broken build in the PR #155 after bump to the version 4.32
of the parent pom.
close #155
> ci: Fix failed build after bump pom

- .github/CONTRIBUTING.md
Fixes #152 
Added documentation to the CONTRIBUTING.md file for this repository in particular. Added details about how to **run** and **test**, as well as a gentle reminder about checking if Jenkins is installed before running this plugin.
> docs: Add contents to CONTRIBUTING.md

- src/main/java/io/jenkins/plugins/conventionalcommits/CurrentVersionStep.java
- src/main/java/io/jenkins/plugins/conventionalcommits/NextVersionStep.java
fix #173 
fix #10
I do some tests with a local main instance and a local remote instance, all seem ok
> fix: 🐛  remote execution

- pom.xml
This should allow the plugin to be installed on more versions of jenkins, rather than the latest.
> Downgrade jenkins to latest lts
